---

- name: Prepare - Set function control facts
  ansible.builtin.set_fact:
    sap_type: "{{ function_list.sap_control_function_current.split('_')[0] | lower }}"
    funct_type: "{{ function_list.sap_control_function_current.split('_')[1] | lower }}"

- name: Prepare - Set header
  ansible.builtin.set_fact:
    sap_control_name_header: "{{ sap_type | upper }} {{ funct_type | capitalize }}"

- name: Prepare - Sort sap_facts_register by sap_control_instance_type_sortorder
  ansible.builtin.set_fact:
    sorted_sap_facts: "{{ (sorted_sap_facts | default([]) | unique) + ( __type_list | difference(sorted_sap_facts | default([]))) }}"
  loop: "{{ sap_control_instance_type_sortorder | reverse if funct_type == 'stop' else sap_control_instance_type_sortorder }}"
  vars:
    __type_list: "{{ sap_facts_register.ansible_facts.sap | selectattr('TYPE', 'equalto', item) | list }}"
  when: 
    - __type_list | length > 0
  
- name: Prepare - SAP Control
  vars:
    sap_control_execute_sid: "{{ item.SID }}"
    sap_control_execute_type: "{{ item.TYPE }}"
    sap_control_execute_instance_nr: "{{ item.NR }}"
    sap_control_execute_instance_type: "{{ item.InstanceType }}"
  ansible.builtin.include_tasks: "sapcontrol.yml"
  loop: "{{ sorted_sap_facts }}"
  when:
    - item.InstanceType | lower == sap_type | lower
...
