---
- name: Pause for 5 Seconds
  ansible.builtin.wait_for:
    timeout: 5

- name: Debug values
  ansible.builtin.debug:
    msg: |
      Async function {{ async_function_dict.test_function }} for SAP SID {{ passed_sap_sid }}
      with retries: {{ async_function_dict.retries | default(0) | int }}
      and delay: {{ async_function_dict.delay | default(0) | int }}
      and until conditions: {{ async_function_dict.until | default([]) }}
      is being executed.

- name: SAP {{ sap_control_name_header }} - Checking if Async action is over by executing sapcontrol -nr {{ passed_sap_nr }} -function {{ async_function_dict.test_function }}
  ansible.builtin.shell: |
    source ~/.profile && sapcontrol -nr {{ passed_sap_nr }} -function {{ async_function_dict.test_function }}
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ passed_sap_sid | lower }}adm"
  register: test_function_result
#  failed_when: "'FAIL' in test_function_result.stdout"
  retries: "{{ async_function_dict.retries | default(0) | int }}"
  delay: "{{ async_function_dict.delay | default(0) | int }}"
  until: async_function_dict.until | default([])
  # until: "{% for condition in async_function_dict.until_conditions %}{{ condition }}{% if not loop.last %} and {% endif %}{% endfor %}"
  failed_when: false

- name: Debug stdout
  ansible.builtin.debug:
    msg: |
       Async function {{ async_function_dict.test_function }} for SAP SID {{ passed_sap_sid }}
       is done with result:
       {{ test_function_result.stdout }}

- name: Fail
  ansible.builtin.fail:
    msg: "FAIL"
