# sap_control_execute_sid: "{{ item.SID }}"
# sap_control_execute_type: "{{ item.Type }}"
# sap_control_execute_instance_nr: "{{ item.InstanceNumber }}"
# sap_control_execute_instance_type: "{{ item.InstanceType }}"
- name: set up facts
  ansible.builtin.set_fact:
    passed_sap_nr: "{{ sap_control_execute_instance_nr }}"
    passed_sap_sid: "{{ sap_control_execute_sid }}"

# Check sapstartsrv
- name: SAP {{ sap_control_name_header }} - sapstartsrv
  ansible.builtin.include_tasks: functions/sapstartsrv.yml

# Execute sapcontrol
- name: SAP {{ sap_control_name_header }} - Executing sapcontrol -nr {{ passed_sap_nr }} -function {{ vars['sap_control_' + funct_type] }}
  ansible.builtin.shell: |
    source ~/.profile && sapcontrol -nr {{ passed_sap_nr }} -function {{ vars['sap_control_' + funct_type] }}
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ passed_sap_sid | lower }}adm"
  register: sapcontrol_status
  failed_when: "'FAIL' in sapcontrol_status.stdout"

# Cleanipc
- name: SAP {{ sap_control_name_header }} - Cleanipc
  ansible.builtin.include_tasks: functions/cleanipc.yml
  when:
    - "'nw' in sap_type"
    - "'stop' in funct_type"
    - "not funct_type is match('.*system')"
